name: Setup Repo Branches

on: workflow_dispatch

jobs:
  setup-repo-settings:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: ['master', 'develop']

    name: Setup Repo Branches

    steps:
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ matrix.branch }}

      - name: Update protected branch settings
        run: |
          curl \
          -X PUT \
          -H "Authorization: token ${SETUP_REPO_GITHUB_TOKEN}" \
          -H "Accept: application/vnd.github.luke-cage-preview+json" \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/branches/${branch}/protection \
          -d '{
                "required_status_checks": {
                    "strict": true,
                    "contexts": []
                },
                "enforce_admins": false,
                "required_pull_request_reviews": {
                    "dismissal_restrictions": {},
                    "dismiss_stale_reviews": true,
                    "required_approving_review_count": 1,
                    "require_code_owner_reviews": false
                },
                "restrictions": null
            }'
        env:
          SETUP_REPO_GITHUB_TOKEN: ${{ secrets.SETUP_REPO_GITHUB_TOKEN }}
          branch: ${{ matrix.branch }}
